source 'https://rubygems.org'

# Sinatra
gem 'sinatra', '>= 2.0.0'

# DataMapper gems
gem 'dm-core'
gem 'dm-timestamps'
gem 'dm-migrations'
gem 'dm-serializer'
gem 'dm-sqlite-adapter'

# Bcrypt
gem 'bcrypt'